'------------------------------------------------------------------------------
' <auto-generated>
'     Este código lo generó una herramienta.
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se regenera el código. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manage

    ''' <summary>
    ''' Control SuccessMessagePlaceHolder.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents SuccessMessagePlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' Control setPassword.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents setPassword As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' contraseña de control.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents password As Global.System.Web.UI.WebControls.TextBox

    ''' <summary>
    ''' Control confirmPassword.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents confirmPassword As Global.System.Web.UI.WebControls.TextBox

    ''' <summary>
    ''' Control changePasswordHolder.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents changePasswordHolder As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' Control changePasswordUserName.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents changePasswordUserName As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' Control CurrentPasswordLabel.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents CurrentPasswordLabel As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' Control CurrentPassword.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents CurrentPassword As Global.System.Web.UI.WebControls.TextBox

    ''' <summary>
    ''' Control NewPasswordLabel.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents NewPasswordLabel As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' Control NewPassword.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents NewPassword As Global.System.Web.UI.WebControls.TextBox

    ''' <summary>
    ''' Control ConfirmNewPasswordLabel.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents ConfirmNewPasswordLabel As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' Control ConfirmNewPassword.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents ConfirmNewPassword As Global.System.Web.UI.WebControls.TextBox
    
End Class
